# Generated by Django 5.2.16 on 2026-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0191_media_scored_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(fields=["end_date"], name="app_episode_end_date_idx"),
        ),
    ]
