# Generated by Django 5.2.16 on 2026-09-30 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0192_music_origin_url"),
        ("app", "0193_add_gcd_source"),
    ]

    operations = []
