# Generated by Django 5.2.16 on 2026-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0194_add_mangabaka_source'),
        ('app', '0194_merge_20260930_1210'),
    ]

    operations = [
    ]
