# Generated by Django 5.2.16 on 2026-10-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0195_merge_20261002_2211'),
        ('app', '0195_video'),
    ]

    operations = [
    ]
