# Generated by Django 5.2.16 on 2026-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0196_merge_0195_merge_20261002_2211_0195_video'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_source_valid',
        ),
        migrations.AlterField(
            model_name='deletedmedia',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemproviderlink',
            name='provider',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metadataproviderpreference',
            name='provider',
            field=models.CharField(blank=True, choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='tmdb', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='pocketcasts', help_text='Podcast provider source for this show', max_length=20),
        ),
        migrations.AlterField(
            model_name='studio',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('tvdb', 'TheTVDB'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('mangabaka', 'MangaBaka'), ('igdb', 'Internet Game Database'), ('imdb', 'IMDb'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('googlebooks', 'Google Books'), ('comicvine', 'Comic Vine'), ('gcd', 'Grand Comics Database'), ('bgg', 'BoardGameGeek'), ('musicbrainz', 'MusicBrainz'), ('pocketcasts', 'Pocket Casts'), ('gpodder', 'GPodder'), ('audiobookshelf', 'Audiobookshelf'), ('storyteller', 'Storyteller'), ('plex', 'Plex'), ('manual', 'Manual'), ('youtube', 'YouTube')], default='tmdb', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['tmdb', 'tvdb', 'mal', 'mangaupdates', 'mangabaka', 'igdb', 'imdb', 'openlibrary', 'hardcover', 'googlebooks', 'comicvine', 'gcd', 'bgg', 'musicbrainz', 'pocketcasts', 'gpodder', 'audiobookshelf', 'storyteller', 'plex', 'manual', 'youtube'])), name='app_item_source_valid'),
        ),
    ]
