# Generated by Django 5.2.16 on 2026-10-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0198_youtube_video_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="rating_only",
            field=models.BooleanField(default=False),
        ),
    ]
