# Generated by Django 5.2.16 on 2026-09-29 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0193_add_gcd_source"),
        ("integrations", "0050_kapowarrinstance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KomgaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Komga server URL")),
                ("api_key", models.TextField(help_text="Encrypted Komga API key")),
                (
                    "create_missing",
                    models.BooleanField(
                        default=True,
                        help_text="Create Floppy items when Komga books cannot be matched",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="How often Komga reading progress is synced",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komga_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Komga account",
                "verbose_name_plural": "Komga accounts",
            },
        ),
        migrations.CreateModel(
            name="KomgaBookLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("komga_book_id", models.CharField(max_length=64)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komga_book_links",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komga_book_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Komga book link",
                "verbose_name_plural": "Komga book links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "komga_book_id"),
                        name="integrations_komgabooklink_unique_user_book",
                    )
                ],
            },
        ),
    ]
