# Generated by Django 5.2.16 on 2026-09-30 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0193_add_gcd_source"),
        ("integrations", "0051_komgaaccount_komgabooklink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="komgaaccount",
            name="api_key",
            field=models.TextField(help_text="Encrypted API key"),
        ),
        migrations.AlterField(
            model_name="komgaaccount",
            name="base_url",
            field=models.URLField(help_text="Server URL"),
        ),
        migrations.AlterField(
            model_name="komgaaccount",
            name="create_missing",
            field=models.BooleanField(
                default=True,
                help_text="Create Floppy items when server items cannot be matched",
            ),
        ),
        migrations.AlterField(
            model_name="komgaaccount",
            name="sync_interval_minutes",
            field=models.PositiveSmallIntegerField(
                default=15, help_text="How often reading progress is synced"
            ),
        ),
        migrations.CreateModel(
            name="KavitaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Server URL")),
                ("api_key", models.TextField(help_text="Encrypted API key")),
                (
                    "create_missing",
                    models.BooleanField(
                        default=True,
                        help_text="Create Floppy items when server items cannot be matched",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="How often reading progress is synced"
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kavita_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kavita account",
                "verbose_name_plural": "Kavita accounts",
            },
        ),
        migrations.CreateModel(
            name="KavitaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kavita_key", models.CharField(max_length=64)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kavita_links",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kavita_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kavita link",
                "verbose_name_plural": "Kavita links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "kavita_key"),
                        name="integrations_kavitalink_unique_user_key",
                    )
                ],
            },
        ),
    ]
