# Generated by Django 5.2.16 on 2026-10-03 20:46

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when the backing column already exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(
            cursor,
            table_name,
        )
        columns = {getattr(column, "name", column[0]) for column in description}
    return column_name in columns


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a named PostgreSQL constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


def _index_exists(schema_editor, table_name, index_name):
    """Return True when the named index already exists on the table."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            constraints = connection.introspection.get_constraints(
                cursor,
                table_name,
            )
        except Exception:  # noqa: BLE001 - introspection quirks are non-fatal
            return False
    return index_name in constraints


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the ALTER when the column is already present."""
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)  # noqa: SLF001
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):  # noqa: SLF001
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfNotExists(migrations.AddIndex):
    """Add an index only when it does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the CREATE INDEX when the index is already present."""
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _index_exists(schema_editor, to_model._meta.db_table, self.index.name):  # noqa: SLF001
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the ADD CONSTRAINT when the constraint is already present."""
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(
            schema_editor,
            to_model._meta.db_table,  # noqa: SLF001
            self.constraint.name,
        ):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class CreateModelIfNotExists(migrations.CreateModel):
    """Create the table only when it is not already there."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the CREATE TABLE on a database that already has it."""
        to_model = to_state.apps.get_model(app_label, self.name)
        table = to_model._meta.db_table  # noqa: SLF001
        with schema_editor.connection.cursor() as cursor:
            existing = schema_editor.connection.introspection.table_names(cursor)
        if table in existing:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0052_kavitaaccount_kavitalink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="ImportChunkReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.CharField(default="persist", max_length=16)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("digest", models.CharField(max_length=64)),
                ("fence", models.PositiveIntegerField()),
                ("rows_persisted", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(default=dict)),
                ("publication_pending", models.BooleanField(default=True)),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        CreateModelIfNotExists(
            name="ImportOverwriteTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("model_label", models.CharField(max_length=100)),
                ("original_pk", models.PositiveBigIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        CreateModelIfNotExists(
            name="PreparedImportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("model_label", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=16)),
                (
                    "payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("persisted_pk", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="chunk_rows",
            field=models.PositiveIntegerField(default=100),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="commit_cursor",
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="fence",
            field=models.PositiveIntegerField(default=0),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="lease_owner",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="phase",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="prepared_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="terminal_error",
            field=models.JSONField(default=dict),
        ),
        AddFieldIfNotExists(
            model_name="importrun",
            name="prepared_state",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        AddConstraintIfNotExists(
            model_name="importrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "trakt"),
                    ("status", "running"),
                    models.Q(("phase", ""), _negated=True),
                ),
                fields=("user", "source"),
                name="one_active_durable_import",
            ),
        ),
        AddFieldIfNotExists(
            model_name="importchunkreceipt",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunk_receipts",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="importoverwritetarget",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overwrite_targets",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="preparedimportentry",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prepared_entries",
                to="integrations.importrun",
            ),
        ),
        AddIndexIfNotExists(
            model_name="importchunkreceipt",
            index=models.Index(
                fields=["publication_pending", "run"],
                name="integration_publica_26faf6_idx",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="importchunkreceipt",
            constraint=models.UniqueConstraint(
                fields=("run", "phase", "start"), name="import_chunk_run_start"
            ),
        ),
        AddIndexIfNotExists(
            model_name="importoverwritetarget",
            index=models.Index(
                fields=["run", "deleted", "ordinal"],
                name="integration_run_id_89c56a_idx",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="importoverwritetarget",
            constraint=models.UniqueConstraint(
                fields=("run", "model_label", "original_pk"),
                name="import_overwrite_original",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="preparedimportentry",
            constraint=models.UniqueConstraint(
                fields=("run", "ordinal"), name="import_entry_run_ordinal"
            ),
        ),
    ]
