# Generated by Django 5.2.17 on 2026-10-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0057_oauthrefreshtoken_replaced_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="psnaccount",
            name="import_existing_playtime",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="PlaytimeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=16)),
                ("media_id", models.CharField(max_length=64)),
                ("minutes", models.PositiveIntegerField(default=0)),
                ("seen_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playtime_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "media_id"),
                        name="unique_playtime_snapshot",
                    )
                ],
            },
        ),
    ]
