# Generated by Django 5.2.17 on 2026-10-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0015_customlist_source_wetrakr"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="tiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tier names and colours for the Tiers view; empty uses the defaults.",
            ),
        ),
        migrations.AddField(
            model_name="customlistitem",
            name="tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Id of the tier this item is placed in; blank means Unranked.",
                max_length=32,
            ),
        ),
    ]
