# Generated by Django 5.2.16 on 2026-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0193_add_gcd_source"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0136_saved_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comic_metadata_source_default",
            field=models.CharField(
                choices=[("comicvine", "Comic Vine"), ("gcd", "Grand Comics Database")],
                default="comicvine",
                help_text="Default metadata provider for Comic details and search tabs.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("comic_metadata_source_default__in", ["comicvine", "gcd"])
                ),
                name="comic_metadata_source_default_valid",
            ),
        ),
    ]
