# Generated by Django 5.2.16 on 2026-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0137_add_gcd_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedview",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("comicissue", "Comic Issue"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                    ("history", "History"),
                ],
                max_length=16,
            ),
        ),
    ]
