# Generated by Django 5.2.16 on 2026-10-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0138_saved_view_history"),
        ("users", "0138_user_tv_auto_move_to_default_provider"),
    ]

    operations = []
