# Generated by Django 5.2.16 on 2026-09-30 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0137_add_gcd_source"),
        ("users", "0138_drop_tile_preference_columns"),
    ]

    operations = []
