# Generated by Django 5.2.16 on 2026-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0193_add_gcd_source"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0139_merge_saved_view_history_and_tv_auto_move"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("comicissue", "Comic Issue"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                    ("all", "All"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "comicissue",
                            "boardgame",
                            "music",
                            "podcast",
                            "all",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
