# Generated by Django 5.2.16 on 2026-10-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0140_search_all_type"),
        ("users", "0140_show_discover_and_recommendations"),
        ("users", "0140_user_seerr_request_settings"),
    ]

    operations = []
