# Generated by Django 5.2.16 on 2026-10-02 14:56

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0194_add_mangabaka_source"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0141_merge_search_all_discover_seerr"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="rating_scale_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="rating_scale",
            field=models.CharField(
                choices=[("10", "1-10 stars"), ("5", "1-5 stars"), ("0", "Disabled")],
                default="10",
                help_text="Preferred rating scale for user scores",
                max_length=2,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating_scale__in", ["10", "5", "0"])),
                name="rating_scale_valid",
            ),
        ),
    ]
