# Generated by Django 5.2.16 on 2026-10-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0139_merge_20260930_1210'),
        ('users', '0142_rating_scale_disabled'),
    ]

    operations = [
    ]
