# Generated by Django 5.2.16 on 2026-10-03 05:12

from django.db import migrations, models


def fill_youtube_posters(apps, schema_editor):
    """Point blank video items at the YouTube thumbnail."""
    Item = apps.get_model("app", "Item")
    videos = Item.objects.filter(media_type="video")
    for item in videos.iterator():
        image = item.image or ""
        if image and not image.startswith("data:"):
            continue
        if not item.media_id:
            continue
        item.image = f"https://img.youtube.com/vi/{item.media_id}/mqdefault.jpg"
        item.save(update_fields=["image"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_youtube_video_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='desc', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='video_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='video_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('critic_rating', 'Critic Rating'), ('title', 'Title'), ('author', 'Author'), ('popularity', 'Popularity'), ('progress', 'Progress'), ('runtime', 'Runtime'), ('time_to_beat', 'Time to Beat'), ('platform', 'Platform'), ('plays', 'Plays'), ('time_watched', 'Time Watched'), ('release_date', 'Release Date'), ('date_added', 'Date Added'), ('start_date', 'Start Date'), ('end_date', 'Last Watched'), ('next_episode_air_date', 'Episode Air Date'), ('time_left', 'Time Left')], default='title', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='video_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=128),
        ),
        migrations.RunPython(fill_youtube_posters, migrations.RunPython.noop),
    ]
