# Generated by Django 5.2.16 on 2026-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0198_youtube_video_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0144_youtube_video_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="video_direction",
            field=models.CharField(
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="desc",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="video_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="video_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="grid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="video_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("critic_rating", "Critic Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("popularity", "Popularity"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("platform", "Platform"),
                    ("plays", "Plays"),
                    ("time_watched", "Time Watched"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "Last Watched"),
                    ("next_episode_air_date", "Episode Air Date"),
                    ("time_left", "Time Left"),
                ],
                default="title",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("video_layout__in", ["grid", "table"])),
                name="video_layout_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "video_sort__in",
                        [
                            "score",
                            "critic_rating",
                            "title",
                            "author",
                            "popularity",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "platform",
                            "plays",
                            "time_watched",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "next_episode_air_date",
                            "time_left",
                        ],
                    )
                ),
                name="video_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("video_direction__in", ["asc", "desc"])),
                name="video_direction_valid",
            ),
        ),
    ]
