# Generated by Django 5.2.16 on 2026-09-29 17:44

from django.db import migrations, models


def seed_card_metadata(apps, schema_editor):
    """Copy tile profiles, or the old global card prefs, onto card_metadata.

    The fork already dropped the global columns in 0138 and stored the
    profiles on tile_metadata. A database that never had that fork migration
    still has the three columns.
    """
    user_model = apps.get_model("users", "User")
    field_names = {field.name for field in user_model._meta.get_fields()}
    pending = []
    for user in user_model.objects.all().iterator():
        if "tile_metadata" in field_names and user.tile_metadata:
            user.card_metadata = user.tile_metadata
        elif "media_card_subtitle_display" in field_names:
            from users.card_metadata import profiles_from_legacy

            user.card_metadata = profiles_from_legacy(
                user.media_card_subtitle_display,
                user.progress_bar,
                user.hide_zero_rating,
            )
        else:
            continue
        pending.append(user)
        if len(pending) >= 500:
            user_model.objects.bulk_update(pending, ["card_metadata"])
            pending = []
    if pending:
        user_model.objects.bulk_update(pending, ["card_metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0145_video_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-media-type subtitle fields shown under a card title",
            ),
        ),
        migrations.RunPython(seed_card_metadata, migrations.RunPython.noop),
    ]
