# Generated by Django 5.2.16 on 2026-09-29 17:44

from django.db import migrations, models


def seed_card_metadata(apps, schema_editor):
    """Copy the three global card prefs onto every media type."""
    user_model = apps.get_model("users", "User")
    from users.card_metadata import profiles_from_legacy

    pending = []
    for user in user_model.objects.all().iterator():
        user.card_metadata = profiles_from_legacy(
            user.media_card_subtitle_display,
            user.progress_bar,
            user.hide_zero_rating,
        )
        pending.append(user)
        if len(pending) >= 500:
            user_model.objects.bulk_update(pending, ["card_metadata"])
            pending = []
    if pending:
        user_model.objects.bulk_update(pending, ["card_metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0145_video_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-media-type subtitle fields shown under a card title",
            ),
        ),
        migrations.RunPython(seed_card_metadata, migrations.RunPython.noop),
    ]
