# Generated by Django 5.2.16 on 2026-09-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0146_card_metadata'),
    ]

    # 0138_drop_tile_preference_columns already removed these on the fork.
    # Repeating the drops fails the migration state.
    operations = []
