# Generated by Django 5.2.17 on 2026-10-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0199_episode_rating_only"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0147_drop_card_preference_columns"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_layout_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table"), ("tiers", "Tiers")],
                default="grid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("custom", "Custom"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                    ("progress", "Progress"),
                    ("status", "Status"),
                    ("release_date", "Release Date"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("platform", "Platform"),
                    ("tier", "Tier"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_sort__in",
                        [
                            "date_added",
                            "custom",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "status",
                            "release_date",
                            "start_date",
                            "end_date",
                            "platform",
                            "tier",
                        ],
                    )
                ),
                name="list_detail_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("list_detail_layout__in", ["grid", "table", "tiers"])
                ),
                name="list_detail_layout_valid",
            ),
        ),
    ]
