# Generated by Django 5.2.16 on 2026-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0200_merge_fork_video_and_upstream'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lists', '0016_customlist_tiers_customlistitem_tier'),
        ('users', '0150_remove_tile_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homescreenrow',
            name='home_screen_row_media_type_valid',
        ),
        migrations.AlterField(
            model_name='homescreenrow',
            name='media_type',
            field=models.CharField(choices=[('all', 'All media'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast'), ('video', 'Video')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='homescreenrow',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['all', 'tv', 'season', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast', 'video'])), name='home_screen_row_media_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_layout__in', ['grid', 'table'])), name='video_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_sort__in', ['score', 'critic_rating', 'title', 'author', 'popularity', 'progress', 'runtime', 'time_to_beat', 'platform', 'plays', 'time_watched', 'release_date', 'date_added', 'start_date', 'end_date', 'next_episode_air_date', 'time_left'])), name='video_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('video_direction__in', ['asc', 'desc'])), name='video_direction_valid'),
        ),
    ]
