# Generated by Django 5.2.16 on 2026-10-01 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0194_add_mangabaka_source"),
        ("events", "0015_event_alert_failed_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_item_null_content_number",
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="event",
            name="release_type",
            field=models.CharField(
                blank=True,
                choices=[("digital", "Digital"), ("physical", "Physical")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_number__isnull", True)),
                fields=("item", "release_type", "region"),
                name="unique_item_release_null_content_number",
            ),
        ),
    ]
